trigger:
- master

stages:
- stage: NonCached
  displayName: 'Non Cached'
  variables:
    AZP_CACHING_CONTENT_FORMAT: SingleTar
    ENABLE_CACHE: 0
  jobs:
  - template: azure-pipelines-jobs.yml

- stage: Cached
  displayName: 'Cached'
  variables:
    AZP_CACHING_CONTENT_FORMAT: SingleTar
  jobs:
  - template: azure-pipelines-jobs.yml

variables:
   skipComponentGovernanceDetection: true
   # # cache the npm cache
   # npm_config_cache: $(Pipeline.Workspace)/.npm
   # dotnpm_CACHE_KEY: '$(dotnpm_CACHE_FALLBACK_KEY) | node.js-with-npm/package-lock.json'
   # dotnpm_CACHE_FALLBACK_KEY: '".npm" | "$(VM_IMAGE)"'
   # cache the node_modules folder
   node_modules_CACHE_KEY: '"node_modules" | "$(VM_IMAGE)" | "AZP_CACHING_CONTENT_FORMAT=$(AZP_CACHING_CONTENT_FORMAT)" | node.js-with-npm/package-lock.json'
