# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # cache the npm cache
  npm_config_cache: $(Pipeline.Workspace)/.npm
  dotnpm_CACHE_KEY: '$(dotnpm_CACHE_FALLBACK_KEY) | package-lock.json'
  dotnpm_CACHE_FALLBACK_KEY: '".npm" | "$(Agent.OS)"'
  # cache the node_modules folder
  node_modules_CACHE_KEY: '"node_modules" | "$(Agent.OS)" | package-lock.json'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# only look for the exact match for node_modules
- task: CacheBeta@1
  inputs:
    key: $(node_modules_CACHE_KEY)
    path: 'node_modules'
    cacheHitVar: NODE_MODULES_RESTORED
  displayName: 'Cache node_modules'
  
# if we didn't get a good match for node_modules, see if we have a recent copy of the .npm cache folder
- task: CacheBeta@1
  inputs:
    key: $(dotnpm_CACHE_KEY)
    restoreKeys: $(dotnpm_CACHE_FALLBACK_KEY)
    path: $(npm_config_change)
  displayName: 'Cache .npm'
  condition: ne(variables.NODE_MODULES_RESTORED, 'true')

- script: |
    npm ci
  displayName: 'npm ci'
  condition: ne(variables.NODE_MODULES_RESTORED, 'true')

- script: npm run-script build
  displayName: 'npm build'