# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  CACHE_KEY: yarn | $(Agent.OS) | yarn.lock
  CACHE_FALLBACK_KEY: yarn | $(Agent.OS)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CacheBeta@1
  inputs:
    key: $(CACHE_KEY)
    restoreKeys: $(CACHE_FALLBACK_KEY)
    path: $(YARN_CACHE_FOLDER)
    cacheHitVar: CACHE_RESTORED 
  displayName: 'Cache yarn packages'

- script: |
    yarn --frozen-lockfile
  displayName: 'Install dependencies'

- script: yarn build
  displayName: 'yarn build'