trigger:
- master

variables:
  uploadVmImage: 'Ubuntu-16.04'
  downloadVmImage: 'Ubuntu-16.04'
  
jobs:
- job: publish
  pool:
    vmImage: $(uploadVmImage)
  steps:
  - script: |  
     mkdir art1
     cd art1
     mkdir firstPublish
     cd firstPublish
     echo "hello world" > hi.txt
     echo "bye" > bye.txt
     echo "goodbye" > goodbye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     cat bye.txt >> goodbye.txt
     cat goodbye.txt >> bye.txt
     
    displayName: Create first folder for artifact
  - task: PublishPipelineArtifact@0
    displayName: "Publish Artifact: drop"
    inputs:
      targetPath: art1
      artifactName: drop
 
