
stages:
- stage: firstrun
  displayName: 'Empty Cache'
  jobs:

  - job: ubuntu_hosted
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      system.debug: true
      # Since vcpkg is a Git submodule, its commit id is stored at /.git/modules/vcpkg/HEAD.
      # vcpkgGitRef: not needed !

    steps:
      - checkout: self
        submodules: recursive
      - task: CacheBeta@1
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt | "$(Agent.OS)" | $(Build.SourcesDirectory)/.git/modules/vcpkg2/HEAD | "gcc" | $(Build.BuildId)
          path: '$(Build.SourcesDirectory)/vcpkg2'
      - task: Cache@2
        displayName: Cache vcpkg GA
        inputs:
          key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt | "$(Agent.OS)" | $(Build.SourcesDirectory)/.git/modules/vcpkg2/HEAD | "gcc" | $(Build.BuildId) | ga
          path: '$(Build.SourcesDirectory)/vcpkg2'
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        displayName: 'Run vcpkg'
        inputs:
          vcpkgArguments: '@$(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt'
          vcpkgDirectory: '$(Build.SourcesDirectory)/vcpkg2'
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        displayName: 'Run CMake with Ninja'
        inputs:
          cmakeListsTxtPath: 'cmakelists.txt/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          ninjaDownloadUrl: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip

- stage: secondrun
  displayName: 'Cached'
  dependsOn: firstrun
  jobs:
  
  - job: ubuntu_hosted
    pool:
      vmImage: 'ubuntu-latest'
  
    variables:
      system.debug: true
      # Since vcpkg is a Git submodule, its commit id is stored at /.git/modules/vcpkg/HEAD.
      # vcpkgGitRef: not needed !
  
    steps:
      - checkout: self
        submodules: recursive
      - task: CacheBeta@1
        displayName: Cache vcpkg
        inputs:
          key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt | "$(Agent.OS)" | $(Build.SourcesDirectory)/.git/modules/vcpkg2/HEAD | "gcc" | $(Build.BuildId)
          path: '$(Build.SourcesDirectory)/vcpkg2'
      - task: Cache@2
        displayName: Cache vcpkg GA
        inputs:
          key: $(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt | "$(Agent.OS)" | $(Build.SourcesDirectory)/.git/modules/vcpkg2/HEAD | "gcc" | $(Build.BuildId) | ga
          path: '$(Build.SourcesDirectory)/vcpkg2'
      - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
        displayName: 'Run vcpkg'
        inputs:
          vcpkgArguments: '@$(Build.SourcesDirectory)/cmakelists.txt/vcpkg_x64-linux.txt'
          vcpkgDirectory: '$(Build.SourcesDirectory)/vcpkg2'
      - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
        displayName: 'Run CMake with Ninja'
        inputs:
          cmakeListsTxtPath: 'cmakelists.txt/CMakeLists.txt'
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          ninjaDownloadUrl: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip

