trigger:
- master

strategy:
  matrix:
    linux 16 Uncached:    
      VM_IMAGE: ubuntu-16.04
      ENABLE_CACHE: 0
    linux 16:    
      VM_IMAGE: ubuntu-16.04
      AZP_CACHING_CONTENT_FORMAT: SingleTar
      AZP_CACHING_TAR: 1

pool:
  vmImage: $(VM_IMAGE)

variables:
  skipComponentGovernanceDetection: true
  system.debug: true

steps:
- checkout: self
  submodules: recursive
- task: CacheBeta@1
  displayName: Cache vcpkg
  inputs:
    key: $(Build.SourcesDirectory)/cpp/cmakelists.txt/vcpkg_x64-linux.txt | "$(Agent.OS)" | "AZP_CACHING_CONTENT_FORMAT=$(AZP_CACHING_CONTENT_FORMAT)" | "gcc"
    path: '$(Build.SourcesDirectory)/cpp/vcpkg2'
- task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
  displayName: 'Run vcpkg'
  inputs:
    vcpkgArguments: '@$(Build.SourcesDirectory)/cpp/cmakelists.txt/vcpkg_x64-linux.txt'
    vcpkgDirectory: '$(Build.SourcesDirectory)/cpp/vcpkg2'
- task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
  displayName: 'Run CMake with Ninja'
  inputs:
    cmakeListsTxtPath: 'cmakelists.txt/CMakeLists.txt'
    useVcpkgToolchainFile: true
    buildWithCMakeArgs: '-- -v'
    ninjaDownloadUrl: https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip

