trigger:
- master

strategy:
  matrix:
    vs2019 Uncached:    
      VM_IMAGE: windows-latest
      ENABLE_CACHE: 0
    vs2019:    
      VM_IMAGE: windows-latest
      AZP_CACHING_CONTENT_FORMAT: SingleTar
      AZP_CACHING_TAR: 1

pool:
  vmImage: $(VM_IMAGE)

variables:
  skipComponentGovernanceDetection: true
  system.debug: true
  vcpkgGitRef: 36d276a19af03210c3fffcdee844b32b9b65334e

steps:
  - task: Cache@2
    displayName: Cache vcpkg
    inputs:
      key: $(Build.SourcesDirectory)/cpp/cmakelists.txt/vcpkg_x64-windows.txt | "$(vcpkgGitRef)" | "$(Agent.OS)" | "vs2019"
      path: '$(Build.SourcesDirectory)/cpp/vcpkg2'
    condition: ne(variables.ENABLE_CACHE, '0')
  - task: lucappa.cmake-ninja-vcpkg-tasks.d855c326-b1c0-4d6f-b1c7-440ade6835fb.run-vcpkg@0
    displayName: 'Run vcpkg'
    inputs:
      vcpkgArguments: '@$(Build.SourcesDirectory)/cpp/cmakelists.txt/vcpkg_x64-windows.txt'
      vcpkgGitCommitId: $(vcpkgGitRef)
      vcpkgDirectory: '$(Build.SourcesDirectory)/cpp/vcpkg2'
      vcpkgGitURL: https://github.com/lukka/vcpkg.git
  - task: lucappa.cmake-ninja-vcpkg-tasks.f2b1ec7d-bc54-4cc8-b9ed-1bc7f37c9dc6.run-cmake@0
    displayName: 'Run CMake with Ninja'
    inputs:
      cmakeListsTxtPath: 'cpp/cmakelists.txt/CMakeLists.txt'
      useVcpkgToolchainFile: true
      vcpkgTriplet: '$(VCPKG_TRIPLET)'
      buildWithCMakeArgs: '-- -v'

